;==================================================================================================
; Settings
;==================================================================================================

OPTIONS_CONTEXT:

; CONF string
.byte 0x43
.byte 0x4F
.byte 0x4E
.byte 0x46

CFG_WS_ENABLED:
.byte 0x00
CFG_DUAL_DPAD_ENABLED:
.byte 0x00
CFG_CLOCK_CONTROL_ENABLED:
.byte 0x00
CFG_OCARINA_ICONS_ENABLED:
.byte 0x00
CFG_HIDE_HUD_ENABLED:
.byte 0x00
CFG_SKIP_GUARD_ENABLED:
.byte 0x00
CFG_SWAP_ENABLED:
.byte 0x00
CFG_UNEQUIP_ENABLED:
.byte 0x00
CFG_B_BUTTON_ITEM_ENABLED:
.byte 0x00
CFG_FLOW_OF_TIME_ENABLED:
.byte 0x00
CFG_INSTANT_ELEGY_ENABLED:
.byte 0x00
CFG_INVERSE_AIM:
.byte 0x00
CFG_INFINITE_HEALTH:
.byte 0x00
CFG_INFINITE_MAGIC:
.byte 0x00
CFG_INFINITE_AMMO:
.byte 0x00
CFG_INFINITE_RUPEES:
.byte 0x00
CFG_FPS_ENABLED:
.byte 0x00
CFG_INVENTORY_EDITOR_ENABLED:
.byte 0x00
CFG_RUPEE_DRAIN:
.byte 0x00
CFG_MUSIC_TRACK_DISPLAY_ENABLED:
.byte 0x00
CFG_OVERLAY_DISPLAY_ENABLED:
.byte 0x00

CFG_BOSS_REMAINS_UNDERWATER_OCARINA:
.byte 0x00
CFG_BOSS_REMAINS_DEKU_HOP:
.byte 0x00
CFG_BOSS_REMAINS_HEALTH_BAR:
.byte 0x00
CFG_BOSS_REMAINS_BOMBCHU_DROPS:
.byte 0x00
CFG_FIERCE_DEITY_GIANTS_MASK:
.byte 0x00

.align 4
